# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-04 15:13
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('dlc', '0002_auto_20160904_1346'),
    ]

    operations = [
        migrations.AddField(
            model_name='dlc',
            name='links',
            field=models.TextField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
