# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-04 15:57
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dlc', '0004_auto_20160904_1523'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dlc',
            name='links',
        ),
    ]
