# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-04 15:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dlc', '0005_remove_dlc_links'),
    ]

    operations = [
        migrations.AddField(
            model_name='dlc',
            name='links',
            field=models.TextField(blank=True),
        ),
    ]
