# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-04 16:04
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dlc', '0010_dlc_links'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dlc',
            name='dlc',
        ),
    ]
