# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-04 16:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dlc', '0011_remove_dlc_dlc'),
    ]

    operations = [
        migrations.AddField(
            model_name='dlc',
            name='dlc',
            field=models.TextField(default='asdf'),
            preserve_default=False,
        ),
    ]
